### PR TITLE
Making one branch for Amanda's work 

### PR DESCRIPTION
**Pull request by AmandaMason23**

### CODE REVIEW

**Comment by jjstickel** [comment]
@AmandaMason23, have you been the only contributor to both the `development` and `amanda` branches? If so, I don't think a PR is needed here.

**Comment by jjstickel** [comment]
Also, I presume this merging of branches will negate PR #6?

**Comment by AmandaMason23** [comment]
@jjstickel Yes, I was trying to see if I could merge them and this was the fastest way for me. Development branch is the only one we need. We can delete amanda.

**Comment by jjstickel** [comment]
> @jjstickel Yes, I was trying to see if I could merge them and this was the fastest way for me. Development branch is the only one we need. We can delete amanda.

OK. Are you also answering yest to my first question - are you also the only contributor to the `development` branch?

**Comment by AmandaMason23** [comment]
> > @jjstickel Yes, I was trying to see if I could merge them and this was the fastest way for me. Development branch is the only one we need. We can delete amanda.
> 
> OK. Are you also answering yest to my first question - are you the only contributor to the `development` branch?

Yes. Ariel implemented some of the valves last summer, but that's it.

**Review by jjstickel — APPROVED** [review]
Please merge this PR (one branch to another). We can do a more extensive review when merging into master.

**Pull request closed without merging**
